# E-Commerce Olist Analytics

## Data Loading

In [15]:
import numpy as np
import pandas as pd

In [16]:
customers= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_customers_dataset.csv")
orders= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_orders_dataset.csv")
order_items= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_order_items_dataset.csv")
payments= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_order_payments_dataset.csv")
reviews= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_order_reviews_dataset.csv")
products= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_products_dataset.csv")
sellers= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_sellers_dataset.csv")
geolocation= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/olist_geolocation_dataset.csv")
category_translation= pd.read_csv("C:/Users/ASHOK/Desktop/Data Analyst/Projects/E-Commerece Olist Project/E-Commerce Olist Dataset/product_category_name_translation.csv")

In [17]:
print('customers:', customers.shape)
print('orders:', orders.shape)
print('order_items:', order_items.shape)
print('payments:', payments.shape)
print('reviews:', reviews.shape)
print('products:', products.shape)
print('sellers:', sellers.shape)
print('geolocation:', geolocation.shape)
print('category_translation:', category_translation.shape)

customers: (99441, 5)
orders: (99441, 8)
order_items: (112650, 7)
payments: (103886, 5)
reviews: (99224, 7)
products: (32951, 9)
sellers: (3095, 4)
geolocation: (1000163, 5)
category_translation: (71, 2)

In [18]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [19]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [20]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [21]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [22]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [23]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [11]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [12]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [13]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## Data Quality Assessment

### customers dataset

In [36]:
print('Customers Dataset Shape:', customers.shape)

Customers Dataset Shape: (99441, 5)

In [37]:
print('Customers Data Types:', customers.dtypes)

Customers Data Types: customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [38]:
print('Customers Missing Values:', customers.isnull().sum())

Customers Missing Values: customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [40]:
print('Customers Missing Values Percentage:', ((customers.isnull().sum()) / (len(customers)) * 100))

Customers Missing Values Percentage: customer_id                 0.0
customer_unique_id          0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
dtype: float64

In [41]:
print('Customers Duplicates:', customers.duplicated().sum())

Customers Duplicates: 0

In [42]:
print('Customers Summary Statistics:', customers.describe())

Customers Summary Statistics:        customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [47]:
print('Customers Info:', customers.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 26.6 MB
Customers Info: None

### orders dataset

In [49]:
print('Orders Dataset Shape:', orders.shape)

Orders Dataset Shape: (99441, 8)

In [50]:
print('Orders Data Types:', orders.dtypes)

Orders Data Types: order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [70]:
print('Orders Missing Values:', orders.isnull().sum())

Orders Missing Values: order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [107]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [52]:
print('Orders Missing Values Percentage:', ((orders.isnull().sum()) / (len(orders)) * 100))

Orders Missing Values Percentage: order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [53]:
print('Orders Duplicates:', orders.duplicated().sum())

Orders Duplicates: 0

In [54]:
print('Orders Summary Statistics:', orders.describe())

Orders Summary Statistics:                                 order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-04-11 10:48:14  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 23:38:46
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

In [55]:
print('Orders Info:', orders.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 52.9 MB
Orders Info: None

### order_items dataset

In [56]:
print('Order_items Dataset Shape:', order_items.shape)

Order_items Dataset Shape: (112650, 7)

In [57]:
print('Order_items Data Types:', order_items.dtypes)

Order_items Data Types: order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [58]:
print('Order_items Missing Values:', order_items.isnull().sum())

Order_items Missing Values: order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [59]:
print('Order_items Missing Values Percentage:', ((order_items.isnull().sum()) / (len(order_items)) * 100))

Order_items Missing Values Percentage: order_id               0.0
order_item_id          0.0
product_id             0.0
seller_id              0.0
shipping_limit_date    0.0
price                  0.0
freight_value          0.0
dtype: float64

In [60]:
print('Order_items Duplicates:', order_items.duplicated().sum())

Order_items Duplicates: 0

In [61]:
print('Order_items Summary Statistics:', order_items.describe())

Order_items Summary Statistics:        order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [62]:
print('Order_items Info:', order_items.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 36.0 MB
Order_items Info: None

### payments dataset

In [63]:
print('Payments Dataset Shape:', payments.shape)

Payments Dataset Shape: (103886, 5)

In [64]:
print('Payments Data Types:', payments.dtypes)

Payments Data Types: order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [65]:
print('Payments Missing Values:', payments.isnull().sum())

Payments Missing Values: order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [66]:
print('Payments Missing Values Percentage:', ((payments.isnull().sum()) / (len(payments)) * 100))

Payments Missing Values Percentage: order_id                0.0
payment_sequential      0.0
payment_type            0.0
payment_installments    0.0
payment_value           0.0
dtype: float64

In [67]:
print('Payments Duplicates:', payments.duplicated().sum())

Payments Duplicates: 0

In [68]:
print('Payments Summary Statistics:', payments.describe())

Payments Summary Statistics:        payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [69]:
print('Payments Info:', payments.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 16.2 MB
Payments Info: None

### reviews dataset

In [71]:
print('Reviews Dataset Shape:', reviews.shape)

Reviews Dataset Shape: (99224, 7)

In [72]:
print('Reviews Data Types:', reviews.dtypes)

Reviews Data Types: review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [74]:
print('Reviews Missing Values:', reviews.isnull().sum())

Reviews Missing Values: review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [75]:
print('Reviews Missing Values Percentage:', ((reviews.isnull().sum()) / (len(reviews)) * 100))

Reviews Missing Values Percentage: review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [76]:
print('Reviews Duplicates:', reviews.duplicated().sum())

Reviews Duplicates: 0

In [77]:
print('Reviews Summary Statistics:', reviews.describe())

Reviews Summary Statistics:        review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [78]:
print('Reviews Info:', reviews.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 39.1 MB
Reviews Info: None

### products dataset

In [79]:
print('Products Dataset Shape:', products.shape)

Products Dataset Shape: (32951, 9)

In [80]:
print('Products Data Types:', products.dtypes)

Products Data Types: product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [81]:
print('Products Missing Values:', products.isnull().sum())

Products Missing Values: product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [82]:
print('Products Missing Values Percentage:', ((products.isnull().sum()) / (len(products)) * 100))

Products Missing Values Percentage: product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

In [83]:
print('Products Duplicates:', products.duplicated().sum())

Products Duplicates: 0

In [84]:
print('Products Summary Statistics:', products.describe())

Products Summary Statistics:        product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000

In [85]:
print('Products Info:', products.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 6.3 MB
Products Info: None

### sellers datasets

In [86]:
print('Sellers Dataset Shape:', sellers.shape)

Sellers Dataset Shape: (3095, 4)

In [87]:
print('Sellers Data Types:', sellers.dtypes)

Sellers Data Types: seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [88]:
print('Sellers Missing Values:', sellers.isnull().sum())

Sellers Missing Values: seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [89]:
print('Sellers Missing Values Percentage:', ((sellers.isnull().sum()) / (len(sellers)) * 100))

Sellers Missing Values Percentage: seller_id                 0.0
seller_zip_code_prefix    0.0
seller_city               0.0
seller_state              0.0
dtype: float64

In [90]:
print('Sellers Duplicates:', sellers.duplicated().sum())

Sellers Duplicates: 0

In [91]:
print('Sellers Summary Statistics:', sellers.describe())

Sellers Summary Statistics:        seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [92]:
print('Sellers Info:', sellers.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 602.2 KB
Sellers Info: None

### geolocation datasets

In [93]:
print('Geolocation Dataset Shape:', geolocation.shape)

Geolocation Dataset Shape: (1000163, 5)

In [94]:
print('Geolocation Data Types:', geolocation.dtypes)

Geolocation Data Types: geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [95]:
print('Geolocation Missing Values:', geolocation.isnull().sum())

Geolocation Missing Values: geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [96]:
print('Geolocation Missing Values Percentage:', ((geolocation.isnull().sum()) / (len(geolocation)) * 100))

Geolocation Missing Values Percentage: geolocation_zip_code_prefix    0.0
geolocation_lat                0.0
geolocation_lng                0.0
geolocation_city               0.0
geolocation_state              0.0
dtype: float64

In [97]:
print('Geolocation Duplicates:', geolocation.duplicated().sum())

Geolocation Duplicates: 261831

In [98]:
print('Geolocation Summary Statistics:', geolocation.describe())

Geolocation Summary Statistics:        geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [99]:
print('Geolocation Info:', geolocation.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 130.3 MB
Geolocation Info: None

### category_translation datasets

In [100]:
print('Category_translation Dataset Shape:', category_translation.shape)

Category_translation Dataset Shape: (71, 2)

In [101]:
print('Category_translation Data Types:', category_translation.dtypes)

Category_translation Data Types: product_category_name            object
product_category_name_english    object
dtype: object

In [102]:
print('Category_translation Missing Values:', category_translation.isnull().sum())

Category_translation Missing Values: product_category_name            0
product_category_name_english    0
dtype: int64

In [103]:
print('Category_translation Missing Values Percentage:', ((category_translation.isnull().sum()) / (len(category_translation)) * 100))

Category_translation Missing Values Percentage: product_category_name            0.0
product_category_name_english    0.0
dtype: float64

In [104]:
print('Category_translation Duplicates:', category_translation.duplicated().sum())

Category_translation Duplicates: 0

In [105]:
print('Category_translation Summary Statistics:', category_translation.describe())

Category_translation Summary Statistics:        product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [106]:
print('Category_translation Info:', category_translation.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 9.2 KB
Category_translation Info: None